#!/bin/sh

function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -a "changevol" -u low -r 9993 -h int:value:"$volume" " Volume: ${volume}%" -t 2000 -i "volume-$1"
}

case $1 in
up)
	pactl set-sink-volume 0 +5%
	send_notification $1
	;;
down)
	pactl set-sink-volume 0 -5%
	send_notification $1
	;;
esac

